#define DEBUG_DELAY_ENABLED
#define DEBUG_PRINT_DELAY_MS 1
#define DEBUG_YIELD_LOOP_DELAY_MS 25

#define ENABLE_DEBUG_LAYER_HAL
#define ENABLE_DEBUG_LAYER_DRIVERS
#define ENABLE_DEBUG_LAYER_SERVICES
#define ENABLE_DEBUG_LAYER_APP
#define ENABLE_DEBUG_LAYER_MAIN
#define ENABLE_DEBUG_LAYER_SIM
//#define ENABLE_DEBUG_LAYER_SIM_ISR
